const movies = [
    { id: 1, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "alice.johnson@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 2, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "bob.smith@example.com", type: "Cartoons", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 3, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "charlie.brown@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 4, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "diana.prince@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 5, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "ethan.hunt@example.com", type: "Cartoons", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 6, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "fiona.apple@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 7, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "george.clooney@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 8, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "hannah.montana@example.com", type: "Cartoons", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 9, name: "Batman",description: " dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc " , genre: "ian.fleming@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" },
    { id: 10, name: "Batman",description: "dbcisjdbcisdcbsidjcbisdjbckjsndc dbcisjdbcisdcbsidjcbisdjbckjsndc c" , genre: "jessica.jones@example.com", type: "Action", cover: "https://m.media-amazon.com/images/M/MV5BZmUwNGU2ZmItMmRiNC00MjhlLTg5YWUtODMyNzkxODYzMmZlXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_SX300.jpg" }
] ;
export default movies;